version: "3.9"
services:
  postgres:
    container_name: py-postgres-stack
    image: postgres
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/data/postgres
    volumes: 
      #- ./constructor.sql:/docker-entrypoint-initdb.d/constructor.sql
      - db:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - postgres
    restart: unless-stopped

  mongodb:
    container_name: py-mongodb-stack
    image: mongo
    env_file: .env
    environment:
      #MONGO_INITDB_ROOT_DATABASE: ${DB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}1:27017"
    networks:
      - mongo
    restart: unless-stopped

  mongo-express:
    container_name: py-mongo-express-stack
    image: mongo-express
    env_file: .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}1/
    ports:
      - 8081:8081
    networks:
      - mongo-express
    restart: unless-stopped
    
  
networks:
  postgres:
    driver: bridge
  mongo:
    driver: bridge
  mongo-express:
    driver: bridge
volumes:
  db:
    driver: local